### PR TITLE
Added sweidnumbr

### PR DESCRIPTION
**Pull request by MansMeg**
Hi!

Here is a first draft where I have added the sweidnumbr to the paper. I could not get it to compile so there might be some LaTeX errors associated with the push. I suggest that you take a pass over the text as the next step since I did not really dared to change too much in your text. Please feel free to edit my parts as much as you like. 

/Måns

### CODE REVIEW

**Comment by antagomir** [comment]
Excellent! I suggest @pitkant will have a look first. At the same go I suggest to check all examples so that they use the aliases that are common to both packages. This way it will be easier to sell it as one piece to the journal. Our respective vignettes can then have more localized material. @pitkant ping me when you're done, and I will then give it a go. Thanks @MansMeg !

**Comment by pitkant** [comment]
Thanks, looks good! I went through the additions and made some changes (mainly things like changing singular nouns to plurals now that the text is usually referring to two packages) that I will push to the rjournal branch after this is merged.

**Comment by MansMeg** [comment]
Great! let me know if you need anything more from me!

**Comment by MansMeg** [comment]
I agree with NIN, I just didnt want to mess around too much with the paper. :)

Thanks!

**Pull request merged**
